name: Trigger auto deployment for album-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/album-ui-AutoDeployTrigger-bfe46925-982c-4796-a4e2-b20957dec17f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ALBUMUI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALBUMUI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALBUMUI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: myapi20240815184609.azurecr.io
          registryUsername: ${{ secrets.ALBUMUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMUI_REGISTRY_PASSWORD }}
          containerAppName: album-ui
          resourceGroup: my-containerapp-rg
          imageToBuild: myapi20240815184609.azurecr.io/album-ui:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


